USE AmazonDB;
-- 1.List all customers who have made purchases of more than $80.
SELECT users.user_name,users.email,SUM(orders.total_amount) AS total_spent
FROM users
JOIN Orders ON users.user_id=orders.user_id
GROUP BY users.user_id
HAVING total_spent>80;

-- 2.Retrieve all orders placed in the last 280 days along with the customer name and email.
SELECT Orders.order_id,Orders.order_date,users.user_name,users.email,Orders.total_amount
FROM Orders
JOIN users ON Orders.user_id=users.user_id
WHERE Orders.order_date>= '2024-06-01'-INTERVAL 30 DAY;

-- 3.. Find the average product price for each category.
SELECT category, AVG(price) AS avg_price
FROM products
GROUP BY category;

-- 4.List all customers who have purchased a product from the category Electronics.
SELECT DISTINCT users.user_name,users.email
FROM users
JOIN Orders ON users.user_id=Orders.user_id
JOIN orderdetails ON Orders.order_id=orderdetails.order_id
JOIN products ON orderdetails.product_id=products.product_id
WHERE products.category='Electronics';

-- 5.Find the total number of products sold and the total revenue generated for each product.
SELECT products.product_name,
	SUM(orderdetails.quantity) AS total_quantity_sold,
    SUM(orderdetails.quantity*products.price) AS total_revenue
FROM orderdetails
JOIN products ON orderdetails.product_id=products.product_id
GROUP BY products.product_id;

-- 6.Update the price of all products in the Books category, increasing it by 10%.
SET SQL_SAFE_UPDATES=0;
ALTER TABLE products
MODIFY price DECIMAL(10,2);

UPDATE products
SET price=ROUND(price*1.10,2)
WHERE category='Books';

SELECT * FROM products;

-- 7.Remove all orders that were placed before 2020.
DELETE FROM orders
WHERE order_date<'2020-01-01';

-- 8.fetch the order details including customer name, product name  and quantity for order placed on 2024-05-01?
SELECT Orders.order_id,users.user_name,products.product_name,orderdetails.quantity
FROM Orders
JOIN users ON Orders.user_id=users.user_id
JOIN orderdetails ON Orders.order_id=orderdetails.order_id
JOIN products ON orderdetails.product_id=products.product_id
Where Orders.order_date='2024-05-01';

-- 9. Fetch all customers and the total number of orders they have placed.
 SELECT users.user_name,users.email,COUNT(Orders.order_id) AS total_orders
 FROM users
 JOIN Orders ON users.user_id=Orders.user_id
 GROUP BY users.user_id;
 
 -- 10.List all customers who purchased more than 3 units of any product, including the product name and total quantity purchased.
SELECT users.user_name,users.email,products.product_name,SUM(orderdetails.quantity) AS total_quantity
FROM users
JOIN Orders ON users.user_id = Orders.user_id
JOIN orderdetails ON Orders.order_id = orderdetails.order_id
JOIN products ON orderdetails.product_id = products.product_id
GROUP BY users.user_id, products.product_id
HAVING total_quantity > 1;

-- 11.Find the total revenue generated by each category along with the category name.
SELECT products.category,SUM(orderdetails.quantity*products.price) AS total_revenue
FROM products
JOIN orderdetails ON products.product_id=orderdetails.product_id
GROUP BY products.category;
